apiVersion: v2
name: sonarr
description: Sonarr (TV) via bjw-s app-template. PostgreSQL and 1Password items. Override ingress, persistence, postgresql in your values.
version: 1.0.0
appVersion: "4.2.2"
kubeVersion: ">=1.22.0-0"
keywords:
  - sonarr
  - tv
  - series
  - bjw-s
  - app-template
home: https://sonarr.tv
sources:
  - https://github.com/Sonarr/Sonarr
maintainers: []
dependencies:
  - name: app-template
    alias: sonarr
    version: "4.6.2"
    repository: https://bjw-s-labs.github.io/helm-charts
  - name: onepassworditem
    version: "1.1.1"
    repository: https://expectedbehaviors.github.io/OnePasswordItem-helm
  - name: postgresql
    version: "16.2.1"
    repository: https://charts.bitnami.com/bitnami
