# Baseline Sonarr. Override ingress host, persistence (existingClaim), postgresql (existingSecret), onepassworditem.items in your values.
sonarr:
  global:
    fullnameOverride: sonarr
  controllers:
    main:
      enabled: true
      defaultContainerOptions:
        image:
          repository: linuxserver/sonarr
          tag: develop
          pullPolicy: Always
      containers:
        main:
          env:
            DOCKER_MODS: linuxserver/mods:radarr-striptracks|ghcr.io/themepark-dev/theme.park:sonarr
            PGID: "1000"
            PUID: "1000"
            TP_HOTIO: "false"
            TP_SCHEME: HTTPS
            TP_THEME: aquamarine
            TZ: UTC
            UMASK: "2"
          probes:
            startup:
              enabled: true
              custom: true
              spec:
                failureThreshold: 90
                periodSeconds: 5
                successThreshold: 1
                tcpSocket:
                  port: 8989
                timeoutSeconds: 1
                initialDelaySeconds: 60
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: "Always"
  service:
    main:
      enabled: true
      ports:
        http:
          enabled: true
          port: 8989
          protocol: HTTP
  ingress:
    main:
      enabled: true
      annotations: {}
      hosts:
        - host: sonarr.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - sonarr.example.com
          secretName: sonarr-tls
  persistence:
    sonarr-secrets:
      enabled: true
      type: secret
      name: sonarr
      globalMounts:
        - path: /config/config.xml
          subPath: config.xml
        - path: /custom-cont-init.d/scripts_init.bash
          subPath: scripts_init.bash
        - path: /config/extended.conf
          subPath: extended.conf
        - path: /config/recyclarr.yaml
          subPath: recyclarr.yaml
    custom-services:
      enabled: true
      type: emptyDir
      globalMounts:
        - path: /custom-services.d
    downloads:
      enabled: true
      type: emptyDir
      globalMounts:
        - path: /downloads

postgresql:
  architecture: standalone
  auth:
    database: sonarr-main
    password: changeme
  primary:
    persistence:
      enabled: true
      size: 5Gi
    name: sonarr-main
    resources:
      requests:
        cpu: "1"
        memory: 2Gi

onepassworditem:
  enabled: true
  items: []
